sudo: false
language: erlang
otp_release:
  - "28.0.2"
cache:
  directories:
    - $HOME/otp/28.0.2
    - $HOME/.cache/rebar3
    - _plt
install: "true"
script: "make travis"
branches:
  only:
    - master
    - develop
notifications:
  email:
    - pj@ezgr.net
